baseURL = "https://thuc.space"
languageCode = "en-us"
title = "Thuc's blog"
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
[menu]
  [[menu.main]]
    identifier = "/"
    name = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "series"
    name = "series"
    url = "/series/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "tags"
    url = "/tags/"
    weight = 3
