version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:
      - checkout
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - run: |
          ls -la $HUGO_BUILD_DIR
      - add_ssh_keys:
          fingerprints:
            - "a7:fa:f1:20:c7:c5:ae:13:55:0a:0a:bb:bb:6e:ac:a2"
      - run:
          name: Clone ledongthuc.github.io
          command: |
            git clone git@github.com:ledongthuc/ledongthuc.github.io.git ~/ledongthuc.github.io
      - run:
          name: Copy build to ledongthuc.github.io
          command: |
            cp -R $HUGO_BUILD_DIR/* ~/ledongthuc.github.io/*
      - run:
          name: Push ledongthuc.github.io
          command: |
            cd ~/ledongthuc.github.io/
            git push origin master
